# Generated by Django 3.0.4 on 2022-07-19 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionSentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_name', models.CharField(max_length=10)),
                ('q_sentence', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.CharField(max_length=200)),
                ('q2', models.CharField(max_length=200)),
                ('q3', models.CharField(max_length=200)),
                ('q_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heart.QuestionSentence')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a1', models.IntegerField(default=0)),
                ('a2', models.IntegerField(default=0)),
                ('a3', models.IntegerField(default=0)),
                ('q_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heart.QuestionSentence')),
            ],
        ),
    ]
